name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Generate APK on apk branch
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Debug APK
      run: bash ./gradlew :app:assembleDebug
              
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk.apk
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
    
    - name: Copy apk to home (~)
      run: cp ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk ~
    
    - name: git config name
      run: git config --global user.name "siddheshkothadi"
    
    - name: git config email
      run: git config --global user.email "realsiddheshko@gmail.com"
    
    - name: git fetch
      run: git fetch origin
    
    - name: Change git branch
      run: git checkout apk
    
    - name: move apk to apk branch
      run: mv ~/app-debug.apk ${{ github.workspace }}
    
    - name: git add
      run: git add app-debug.apk
    
    - name: git commit
      run: git commit -m "apk"
    
#    - name: git push
#      run: git push origin
