name: Generate and push apk to apk branch
on:
  push:
    branches: [master]

jobs:
  build_apk:
    name: Generate and push apk to apk branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
         java-version: 1.8

      # Cache gradle
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant Permission to Execute gradle
        run: chmod +x gradlew
      - name: Grant Permission to execute script.sh
        run: chmod +x script.sh
        
      - name: Generate APKs and upload artifacts
        run: bash ./gradlew :app:assembleDebug --stacktrace
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Push APKs to apk branch
        run: ./script.sh
